name:                untyped-lambda-calculus
version:             0.1.0.0
github:              "jamestmartin/untyped-lambda-calculus"
license:             GPL-3
author:              "James Martin"
maintainer:          "james@jtmar.me"
copyright:           "2019 James Martin"
synopsis:            "A simple implementation of the untyped lambda calculus as an exercise."
category:            LambdaCalculus
description:         Please see the README on GitHub at <https://github.com/jamestmartin/untyped-lambda-calculus#readme>

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- mtl >= 2.2 && < 3
- parsec >= 3.1 && < 4
- transformers >= 0.5.6 && < 0.6

library:
  source-dirs: src

executables:
  untyped-lambda-calculus-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - untyped-lambda-calculus
