name:                jtm-lambda-calculus
version:             0.1.0.0
github:              "jamestmartin/lambda-calculus"
license:             GPL-3
author:              "James Martin"
maintainer:          "james@jtmar.me"
copyright:           "2019-2020 James Martin"
synopsis:            "A simple implementation of the lambda calculus."
category:            LambdaCalculus
description:         Please see the README on GitHub at <https://github.com/jamestmartin/lambda-calculus#readme>

extra-source-files:
- README.md

default-extensions:
- ImportQualifiedPost
- OverloadedStrings
- ViewPatterns

dependencies:
- base >= 4.13 && < 5
- parsec >= 3.1 && < 4
- text >= 1.2 && < 2
- text-show >= 3.8 && < 4
- unordered-containers >= 0.2.10 && < 0.3

library:
  source-dirs: src

executables:
  jtm-lambda-calculus:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jtm-lambda-calculus

tests:
  jtm-lambda-calculus-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jtm-lambda-calculus
    - generic-random >= 1.2 && < 2
    - QuickCheck >= 2.13 && < 3
    - tasty >= 1.2 && < 2
    - tasty-hunit >= 0.10 && < 0.11
    - tasty-quickcheck >= 0.10.1 && < 0.11
