name:                ivo
version:             0.1.0.0
github:              "ivolang/ivo"
license:             GPL-3
author:              "James Martin"
maintainer:          "james@jtmar.me"
copyright:           "2019-2021 James Martin"
synopsis:            "A useless programming language for useless people."
category:            Language
description:         Please see the README on GitHub at <https://github.com/ivolang/ivo#readme>

extra-source-files:
- README.md

dependencies:
- base >= 4.14 && < 5
- monad-loops >= 0.4.3 && < 0.5
- mtl >= 2.2 && < 3
- parsec >= 3.1 && < 4
- recursion-schemes >= 5.2 && < 6
- text >= 1.2 && < 2
- unordered-containers >= 0.2.13 && < 0.3

default-extensions:
- BlockArguments
- ConstraintKinds
- DefaultSignatures
- DeriveFoldable
- DeriveFunctor
- DeriveTraversable
- EmptyCase
- EmptyDataDeriving
- FlexibleContexts
- FlexibleInstances
- ImportQualifiedPost
- InstanceSigs
- LambdaCase
- MultiParamTypeClasses
- NamedFieldPuns
- OverloadedStrings
- PatternSynonyms
- ScopedTypeVariables
- StandaloneDeriving
- TypeFamilies
- ViewPatterns

library:
  source-dirs: src
  ghc-options:
  - -Weverything
  # Useless Safe Haskell warnings
  - -Wno-missing-safe-haskell-mode
  - -Wno-unsafe
  - -Wno-safe
  # Other stupid warnings
  - -Wno-implicit-prelude
  - -Wno-missing-deriving-strategies
  # Less stupid warnings, but I still don't care
  - -Wno-all-missed-specialisations
  - -Wno-missing-local-signatures
  # Explicit import lists are generally a good thing, but I don't want them
  # in certain cases (e.g. importing my own modules, task-specific modules like the parser).
  - -Wno-missing-import-lists

executables:
  ivo:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wno-missing-export-lists
    - -Wno-monomorphism-restriction
    - -Wno-unused-do-bind
    dependencies:
    - ivo
    - exceptions >= 0.10.4 && < 0.11
    - haskeline >= 0.8 && < 1

tests:
  ivo-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ivo
    - tasty >= 1.2 && < 2
    - tasty-hunit >= 0.10 && < 0.11
